In [76]:
import pandas as pd 
import numpy as np

In [77]:
df = pd.read_csv(
    r"C:\Users\asus\Downloads\anand college 45 days traing\project\Laptop\data\laptop_price.csv",
    encoding='latin1'
)

In [78]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [79]:
df['Company'].nunique()

19

In [80]:
df.duplicated().sum()

np.int64(0)

In [81]:
df['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: count, dtype: int64

In [82]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [83]:
df.drop_duplicates()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [84]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [85]:
df['Company'].unique()

<StringArray>
[    'Apple',        'HP',      'Acer',      'Asus',      'Dell',    'Lenovo',
     'Chuwi',       'MSI', 'Microsoft',   'Toshiba',    'Huawei',    'Xiaomi',
      'Vero',     'Razer',  'Mediacom',   'Samsung',    'Google',   'Fujitsu',
        'LG']
Length: 19, dtype: str

In [86]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [87]:
df['Ram'].unique()

<StringArray>
['8GB', '16GB', '4GB', '2GB', '12GB', '6GB', '32GB', '24GB', '64GB']
Length: 9, dtype: str

In [88]:
Ram_dic  = {'8GB':1, '16GB':2, '4GB':3, '2GB':4, '12GB':5, '6GB':6, '32GB':7, '24GB':8, '64GB':9}
df['Ram'] = df['Ram'].map(Ram_dic)

In [89]:
Ram_dic

{'8GB': 1,
 '16GB': 2,
 '4GB': 3,
 '2GB': 4,
 '12GB': 5,
 '6GB': 6,
 '32GB': 7,
 '24GB': 8,
 '64GB': 9}

In [90]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,1,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,1,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,2,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,1,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,3,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,2,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,3,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00

In [91]:
df['Product'].unique()

<StringArray>
[                              'MacBook Pro',
                               'Macbook Air',
                                    '250 G6',
                                  'Aspire 3',
                           'ZenBook UX430UN',
                                   'Swift 3',
                             'Inspiron 3567',
                               'MacBook 12"',
                         'IdeaPad 320-15IKB',
                                    'XPS 13',
 ...
                               'GE62 Apache',
                            'Yoga 500-14IBD',
                      'ZenBook UX305CA-UBM1',
                            'Aspire ES1-531',
                       'Pavilion 15-AW003nv',
                          'Stream 11-Y000na',
 'X556UJ-XO044T (i7-6500U/4GB/500GB/GeForce',
                            'Yoga 500-14ISK',
       '15-AC110nv (i7-6500U/6GB/1TB/Radeon',
       'X553SA-XX031T (N3050/4GB/500GB/W10)']
Length: 618, dtype: str

In [92]:
df = df.sort_values(by='Company').reset_index(drop=True)

In [93]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,659,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,Gaming,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,1TB HDD,Nvidia GeForce GTX 1050,Linux,2.4kg,709.00
1,80,Acer,Aspire A515-51G-32MX,Notebook,15.6,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,1TB HDD,Nvidia GeForce MX130,Windows 10,2.2kg,530.00
2,330,Acer,Aspire 5,Notebook,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,1,256GB SSD,AMD Radeon RX 540,Windows 10,2.2kg,659.00
3,332,Acer,Aspire E5-575,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,6,1TB HDD,Intel HD Graphics 620,Windows 10,2.23kg,549.00
4,377,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,3,128GB SSD,AMD Radeon R5,Windows 10,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),Notebook,13.3,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.35kg,196.00
1299,888,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00
1300,188,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00
1301,521,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95
1302,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90

In [137]:
df['Inches'].unique()

array([ 1,  2,  5,  7,  4, 11, 12,  6, 15,  8, 10,  3, 17, 16,  9, 14])

In [95]:
TypeName_dic = {'Notebook':1,          'Ultrabook':2,             'Gaming':3,
 '2 in 1 Convertible':4,            'Netbook':5,        'Workstation':6}
df['TypeName'] = df['TypeName'].map(TypeName_dic )

In [96]:
TypeName_dic

{'Notebook': 1,
 'Ultrabook': 2,
 'Gaming': 3,
 '2 in 1 Convertible': 4,
 'Netbook': 5,
 'Workstation': 6}

In [97]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,659,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,1TB HDD,Nvidia GeForce GTX 1050,Linux,2.4kg,709.00
1,80,Acer,Aspire A515-51G-32MX,1,15.6,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,1TB HDD,Nvidia GeForce MX130,Windows 10,2.2kg,530.00
2,330,Acer,Aspire 5,1,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,1,256GB SSD,AMD Radeon RX 540,Windows 10,2.2kg,659.00
3,332,Acer,Aspire E5-575,1,15.6,1366x768,Intel Core i5 7200U 2.5GHz,6,1TB HDD,Intel HD Graphics 620,Windows 10,2.23kg,549.00
4,377,Acer,Aspire 3,1,15.6,1366x768,AMD A9-Series 9420 3GHz,3,128GB SSD,AMD Radeon R5,Windows 10,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,13.3,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.35kg,196.00
1299,888,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00
1300,188,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00
1301,521,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95
1302,196,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90

In [98]:
df['Memory'].unique()

<StringArray>
[                      '1TB HDD',                     '256GB SSD',
                     '128GB SSD',                     '500GB HDD',
            '32GB Flash Storage',           '128GB Flash Storage',
                      '16GB SSD',          '256GB SSD +  1TB HDD',
                      '32GB SSD',          '128GB SSD +  1TB HDD',
            '16GB Flash Storage',           '512GB Flash Storage',
                     '512GB SSD',           '256GB Flash Storage',
            '64GB Flash Storage',          '512GB SSD +  2TB HDD',
                       '2TB HDD',          '512GB SSD +  1TB HDD',
                       '1TB SSD',                     '128GB HDD',
        '256GB SSD +  256GB SSD',        '512GB SSD +  512GB SSD',
        '256GB SSD +  500GB HDD',                      '64GB SSD',
            '1TB SSD +  1TB HDD',          '256GB SSD +  2TB HDD',
                  '1.0TB Hybrid',          '128GB SSD +  2TB HDD',
        '512GB SSD +  256GB SSD', '64GB Flash Storage +  1TB HDD',
                     '240GB SSD',                       '8GB SSD',
                     '1.0TB HDD',                     '180GB SSD',
     '512GB SSD +  1.0TB Hybrid',            '1TB HDD +  1TB HDD',
     '256GB SSD +  1.0TB Hybrid',                  '508GB Hybrid',
                      '32GB HDD']
Length: 39, dtype: str

In [99]:
memory_dic = {
    '500GB HDD': 1,
    '2TB HDD': 2,
    '1TB HDD': 3,
    '256GB SSD': 4,
    '128GB SSD +  1TB HDD': 5,
    '128GB SSD': 6,
    '256GB SSD +  1TB HDD': 7,
    '512GB SSD +  1TB HDD': 8,
    '1TB SSD +  1TB HDD': 9,
    '32GB Flash Storage': 10,
    '1.0TB Hybrid': 11,
    '512GB SSD': 12,
    '1TB SSD': 13,
    '32GB SSD': 14,
    '16GB Flash Storage': 15,
    '16GB SSD': 16,
    '64GB Flash Storage': 17,
    '64GB SSD': 18,
    '256GB SSD +  500GB HDD': 19,
    '240GB SSD': 20,
    '256GB SSD +  256GB SSD': 21,
    '256GB SSD +  2TB HDD': 22,
    '512GB SSD +  2TB HDD': 23,
    '1.0TB HDD': 24,
    '512GB SSD +  1.0TB Hybrid': 25,
    '256GB SSD +  1.0TB Hybrid': 26,
    '128GB SSD +  2TB HDD': 27,
    '512GB SSD +  256GB SSD': 28,
    '512GB Flash Storage': 29,
    '256GB Flash Storage': 30,
    '128GB Flash Storage': 31,
    '64GB Flash Storage +  1TB HDD': 32,
    '128GB HDD': 33,
    '32GB HDD': 34,
    '508GB Hybrid': 35,
    '180GB SSD': 36,
    '1TB HDD +  1TB HDD': 37,
    '8GB SSD': 38,
    '512GB SSD +  512GB SSD': 39
}
df['Memory'] = df['Memory'].map(memory_dic)

In [100]:
memory_dic

{'500GB HDD': 1,
 '2TB HDD': 2,
 '1TB HDD': 3,
 '256GB SSD': 4,
 '128GB SSD +  1TB HDD': 5,
 '128GB SSD': 6,
 '256GB SSD +  1TB HDD': 7,
 '512GB SSD +  1TB HDD': 8,
 '1TB SSD +  1TB HDD': 9,
 '32GB Flash Storage': 10,
 '1.0TB Hybrid': 11,
 '512GB SSD': 12,
 '1TB SSD': 13,
 '32GB SSD': 14,
 '16GB Flash Storage': 15,
 '16GB SSD': 16,
 '64GB Flash Storage': 17,
 '64GB SSD': 18,
 '256GB SSD +  500GB HDD': 19,
 '240GB SSD': 20,
 '256GB SSD +  256GB SSD': 21,
 '256GB SSD +  2TB HDD': 22,
 '512GB SSD +  2TB HDD': 23,
 '1.0TB HDD': 24,
 '512GB SSD +  1.0TB Hybrid': 25,
 '256GB SSD +  1.0TB Hybrid': 26,
 '128GB SSD +  2TB HDD': 27,
 '512GB SSD +  256GB SSD': 28,
 '512GB Flash Storage': 29,
 '256GB Flash Storage': 30,
 '128GB Flash Storage': 31,
 '64GB Flash Storage +  1TB HDD': 32,
 '128GB HDD': 33,
 '32GB HDD': 34,
 '508GB Hybrid': 35,
 '180GB SSD': 36,
 '1TB HDD +  1TB HDD': 37,
 '8GB SSD': 38,
 '512GB SSD +  512GB SSD': 39}

In [101]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,659,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,3,Nvidia GeForce GTX 1050,Linux,2.4kg,709.00
1,80,Acer,Aspire A515-51G-32MX,1,15.6,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,3,Nvidia GeForce MX130,Windows 10,2.2kg,530.00
2,330,Acer,Aspire 5,1,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,1,4,AMD Radeon RX 540,Windows 10,2.2kg,659.00
3,332,Acer,Aspire E5-575,1,15.6,1366x768,Intel Core i5 7200U 2.5GHz,6,3,Intel HD Graphics 620,Windows 10,2.23kg,549.00
4,377,Acer,Aspire 3,1,15.6,1366x768,AMD A9-Series 9420 3GHz,3,6,AMD Radeon R5,Windows 10,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,13.3,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,10,Intel HD Graphics 400,Windows 10,1.35kg,196.00
1299,888,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,4,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00
1300,188,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,4,Nvidia GeForce MX150,No OS,1.95kg,1199.00
1301,521,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,4,Nvidia GeForce MX150,No OS,1.95kg,1399.95
1302,196,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,4,Nvidia GeForce MX150,No OS,1.3kg,999.90

In [102]:
df['Gpu'].unique()

<StringArray>
[ 'Nvidia GeForce GTX 1050',     'Nvidia GeForce MX130',
        'AMD Radeon RX 540',    'Intel HD Graphics 620',
            'AMD Radeon R5',    'Intel HD Graphics 520',
     'Nvidia GeForce 940MX',    'Intel HD Graphics 400',
 'Nvidia GeForce GTX 940MX',     'Nvidia GeForce MX150',
 ...
      'Nvidia Quadro M500M',       'AMD Radeon R7 M460',
            'AMD Radeon R3',    'Intel HD Graphics 540',
       'AMD Radeon R9 M385',           'AMD R17M-M1-70',
       'Nvidia GTX 980 SLI',        'ARM Mali T860 MP4',
           'AMD Radeon 540',      'Nvidia GeForce 930M']
Length: 110, dtype: str

In [103]:
df['OpSys'].unique()

<StringArray>
[       'Linux',   'Windows 10',    'Chrome OS',     'Mac OS X',
        'macOS', 'Windows 10 S',        'No OS',    'Windows 7',
      'Android']
Length: 9, dtype: str

In [104]:
OpSys_dic = {'Windows 10':1,'No OS':2,        'Linux':3,    'Windows 7':4,
    'Chrome OS':5, 'Windows 10 S':6,        'macOS':7,     'Mac OS X':8,
      'Android':9}
df['OpSys'] = df['OpSys'].map(OpSys_dic)

In [105]:
OpSys_dic

{'Windows 10': 1,
 'No OS': 2,
 'Linux': 3,
 'Windows 7': 4,
 'Chrome OS': 5,
 'Windows 10 S': 6,
 'macOS': 7,
 'Mac OS X': 8,
 'Android': 9}

In [106]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,659,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,3,Nvidia GeForce GTX 1050,3,2.4kg,709.00
1,80,Acer,Aspire A515-51G-32MX,1,15.6,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,3,Nvidia GeForce MX130,1,2.2kg,530.00
2,330,Acer,Aspire 5,1,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,1,4,AMD Radeon RX 540,1,2.2kg,659.00
3,332,Acer,Aspire E5-575,1,15.6,1366x768,Intel Core i5 7200U 2.5GHz,6,3,Intel HD Graphics 620,1,2.23kg,549.00
4,377,Acer,Aspire 3,1,15.6,1366x768,AMD A9-Series 9420 3GHz,3,6,AMD Radeon R5,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,13.3,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,10,Intel HD Graphics 400,1,1.35kg,196.00
1299,888,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,4,Nvidia GeForce 940MX,1,1.28kg,935.00
1300,188,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,4,Nvidia GeForce MX150,2,1.95kg,1199.00
1301,521,Xiaomi,Mi Notebook,1,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,4,Nvidia GeForce MX150,2,1.95kg,1399.95
1302,196,Xiaomi,Mi Notebook,2,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,4,Nvidia GeForce MX150,2,1.3kg,999.90

In [107]:
df['Inches'].nunique()

18

In [108]:
Inches_dic ={15.6:1, 14:2 , 17:3 , 17.3:4, 13.3:5, 12.5:6, 11.6:7, 12.3:8, 18.4:9, 15.:10 , 12. :11,
       15.4:12, 13.:13 , 13.5:14, 14.1:15, 11.3:16, 13.9:17, 10.1:18}
df['Inches'] = df['Inches'].map(Inches_dic)

In [109]:
Inches_dic

{15.6: 1,
 14: 2,
 17: 3,
 17.3: 4,
 13.3: 5,
 12.5: 6,
 11.6: 7,
 12.3: 8,
 18.4: 9,
 15.0: 10,
 12.0: 11,
 15.4: 12,
 13.0: 13,
 13.5: 14,
 14.1: 15,
 11.3: 16,
 13.9: 17,
 10.1: 18}

In [110]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,659,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,3,Nvidia GeForce GTX 1050,3,2.4kg,709.00
1,80,Acer,Aspire A515-51G-32MX,1,1,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,3,Nvidia GeForce MX130,1,2.2kg,530.00
2,330,Acer,Aspire 5,1,1,1366x768,AMD A12-Series 9720P 2.7GHz,1,4,AMD Radeon RX 540,1,2.2kg,659.00
3,332,Acer,Aspire E5-575,1,1,1366x768,Intel Core i5 7200U 2.5GHz,6,3,Intel HD Graphics 620,1,2.23kg,549.00
4,377,Acer,Aspire 3,1,1,1366x768,AMD A9-Series 9420 3GHz,3,6,AMD Radeon R5,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,10,Intel HD Graphics 400,1,1.35kg,196.00
1299,888,Xiaomi,Mi Notebook,2,5,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,4,Nvidia GeForce 940MX,1,1.28kg,935.00
1300,188,Xiaomi,Mi Notebook,1,1,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,4,Nvidia GeForce MX150,2,1.95kg,1199.00
1301,521,Xiaomi,Mi Notebook,1,1,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,4,Nvidia GeForce MX150,2,1.95kg,1399.95
1302,196,Xiaomi,Mi Notebook,2,5,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,4,Nvidia GeForce MX150,2,1.3kg,999.90

In [111]:
df['Cpu'].nunique()

118

In [112]:
df = df.drop(columns=['laptop_ID'])

In [113]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,1,3,Nvidia GeForce GTX 1050,3,2.4kg,709.00
1,Acer,Aspire A515-51G-32MX,1,1,Full HD 1920x1080,Intel Core i3 7130U 2.7GHz,3,3,Nvidia GeForce MX130,1,2.2kg,530.00
2,Acer,Aspire 5,1,1,1366x768,AMD A12-Series 9720P 2.7GHz,1,4,AMD Radeon RX 540,1,2.2kg,659.00
3,Acer,Aspire E5-575,1,1,1366x768,Intel Core i5 7200U 2.5GHz,6,3,Intel HD Graphics 620,1,2.23kg,549.00
4,Acer,Aspire 3,1,1,1366x768,AMD A9-Series 9420 3GHz,3,6,AMD Radeon R5,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,3,10,Intel HD Graphics 400,1,1.35kg,196.00
1299,Xiaomi,Mi Notebook,2,5,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,1,4,Nvidia GeForce 940MX,1,1.28kg,935.00
1300,Xiaomi,Mi Notebook,1,1,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,1,4,Nvidia GeForce MX150,2,1.95kg,1199.00
1301,Xiaomi,Mi Notebook,1,1,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,2,4,Nvidia GeForce MX150,2,1.95kg,1399.95
1302,Xiaomi,Mi Notebook,2,5,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,1,4,Nvidia GeForce MX150,2,1.3kg,999.90

In [114]:
df['Product'].nunique()

618

In [115]:
df['ScreenResolution'].unique()

<StringArray>
[                            'Full HD 1920x1080',
                                      '1366x768',
                            'IPS Panel 1366x768',
     'IPS Panel Full HD / Touchscreen 1920x1080',
                   'IPS Panel Full HD 1920x1080',
                'IPS Panel Touchscreen 1366x768',
                                      '1600x900',
            'IPS Panel Retina Display 2304x1440',
            'IPS Panel Retina Display 2560x1600',
            'IPS Panel Retina Display 2880x1800',
                                      '1440x900',
               'IPS Panel 4K Ultra HD 3840x2160',
               'Full HD / Touchscreen 1920x1080',
                          'Touchscreen 1366x768',
                  'IPS Panel Quad HD+ 3200x1800',
                                     '1920x1080',
               'Touchscreen / Full HD 1920x1080',
           '4K Ultra HD / Touchscreen 3840x2160',
                            'Quad HD+ 3200x1800',
            'IPS Panel Retina Display 2736x1824',
                         '4K Ultra HD 3840x2160',
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160',
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
              'Quad HD+ / Touchscreen 3200x1800',
                                     '2560x1440',
              'Touchscreen / Quad HD+ 3200x1800',
                         'Touchscreen 2560x1440',
                           'IPS Panel 2560x1440',
                         'Touchscreen 2400x1600',
    'IPS Panel Quad HD+ / Touchscreen 3200x1800',
                    'IPS Panel Full HD 1366x768',
                   'IPS Panel Full HD 2160x1440',
               'IPS Panel Touchscreen 1920x1200',
               'IPS Panel Touchscreen 2560x1440',
                  'IPS Panel Quad HD+ 2560x1440',
                   'IPS Panel Full HD 2560x1440',
                   'IPS Panel Full HD 1920x1200',
                         'Touchscreen 2256x1504',
           'Touchscreen / 4K Ultra HD 3840x2160',
               'IPS Panel Touchscreen 2400x1600']
Length: 40, dtype: str

In [116]:
ScreenResolution_dic = { 'Full HD 1920x1080': 0,
    '1366x768': 1,
    'IPS Panel 1366x768': 2,
    'IPS Panel Full HD / Touchscreen 1920x1080': 3,
    'IPS Panel Full HD 1920x1080': 4,
    'IPS Panel Touchscreen 1366x768': 5,
    '1600x900': 6,
    'IPS Panel Retina Display 2304x1440': 7,
    'IPS Panel Retina Display 2560x1600': 8,
    'IPS Panel Retina Display 2880x1800': 9,
    '1440x900': 10,
    'IPS Panel 4K Ultra HD 3840x2160': 11,
    'Full HD / Touchscreen 1920x1080': 12,
    'Touchscreen 1366x768': 13,
    'IPS Panel Quad HD+ 3200x1800': 14,
    '1920x1080': 15,
    'Touchscreen / Full HD 1920x1080': 16,
    '4K Ultra HD / Touchscreen 3840x2160': 17,
    'Quad HD+ 3200x1800': 18,
    'IPS Panel Retina Display 2736x1824': 19,
    '4K Ultra HD 3840x2160': 20,
    'IPS Panel Touchscreen / 4K Ultra HD 3840x2160': 21,
    'IPS Panel 4K Ultra HD / Touchscreen 3840x2160': 22,
    'Quad HD+ / Touchscreen 3200x1800': 23,
    'IPS Panel Full HD 1920x1200': 24,
    'Touchscreen 2256x1504': 25,
    'Touchscreen / 4K Ultra HD 3840x2160': 26,
    'IPS Panel Touchscreen 2400x1600': 27}
df['ScreenResolution'] = df['ScreenResolution'].map(ScreenResolution_dic)

In [117]:
ScreenResolution_dic

{'Full HD 1920x1080': 0,
 '1366x768': 1,
 'IPS Panel 1366x768': 2,
 'IPS Panel Full HD / Touchscreen 1920x1080': 3,
 'IPS Panel Full HD 1920x1080': 4,
 'IPS Panel Touchscreen 1366x768': 5,
 '1600x900': 6,
 'IPS Panel Retina Display 2304x1440': 7,
 'IPS Panel Retina Display 2560x1600': 8,
 'IPS Panel Retina Display 2880x1800': 9,
 '1440x900': 10,
 'IPS Panel 4K Ultra HD 3840x2160': 11,
 'Full HD / Touchscreen 1920x1080': 12,
 'Touchscreen 1366x768': 13,
 'IPS Panel Quad HD+ 3200x1800': 14,
 '1920x1080': 15,
 'Touchscreen / Full HD 1920x1080': 16,
 '4K Ultra HD / Touchscreen 3840x2160': 17,
 'Quad HD+ 3200x1800': 18,
 'IPS Panel Retina Display 2736x1824': 19,
 '4K Ultra HD 3840x2160': 20,
 'IPS Panel Touchscreen / 4K Ultra HD 3840x2160': 21,
 'IPS Panel 4K Ultra HD / Touchscreen 3840x2160': 22,
 'Quad HD+ / Touchscreen 3200x1800': 23,
 'IPS Panel Full HD 1920x1200': 24,
 'Touchscreen 2256x1504': 25,
 'Touchscreen / 4K Ultra HD 3840x2160': 26,
 'IPS Panel Touchscreen 2400x1600': 27}

In [118]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,0.0,Intel Core i5 7300HQ 2.5GHz,1,3,Nvidia GeForce GTX 1050,3,2.4kg,709.00
1,Acer,Aspire A515-51G-32MX,1,1,0.0,Intel Core i3 7130U 2.7GHz,3,3,Nvidia GeForce MX130,1,2.2kg,530.00
2,Acer,Aspire 5,1,1,1.0,AMD A12-Series 9720P 2.7GHz,1,4,AMD Radeon RX 540,1,2.2kg,659.00
3,Acer,Aspire E5-575,1,1,1.0,Intel Core i5 7200U 2.5GHz,6,3,Intel HD Graphics 620,1,2.23kg,549.00
4,Acer,Aspire 3,1,1,1.0,AMD A9-Series 9420 3GHz,3,6,AMD Radeon R5,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,0.0,Intel Atom X5-Z8350 1.44GHz,3,10,Intel HD Graphics 400,1,1.35kg,196.00
1299,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 6200U 2.3GHz,1,4,Nvidia GeForce 940MX,1,1.28kg,935.00
1300,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i5 8250U 1.6GHz,1,4,Nvidia GeForce MX150,2,1.95kg,1199.00
1301,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i7 8550U 1.8GHz,2,4,Nvidia GeForce MX150,2,1.95kg,1399.95
1302,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 7200U 2.5GHz,1,4,Nvidia GeForce MX150,2,1.3kg,999.90

In [119]:
df = df.drop(columns=['Gpu'])

In [120]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,OpSys,Weight,Price_euros
0,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,0.0,Intel Core i5 7300HQ 2.5GHz,1,3,3,2.4kg,709.00
1,Acer,Aspire A515-51G-32MX,1,1,0.0,Intel Core i3 7130U 2.7GHz,3,3,1,2.2kg,530.00
2,Acer,Aspire 5,1,1,1.0,AMD A12-Series 9720P 2.7GHz,1,4,1,2.2kg,659.00
3,Acer,Aspire E5-575,1,1,1.0,Intel Core i5 7200U 2.5GHz,6,3,1,2.23kg,549.00
4,Acer,Aspire 3,1,1,1.0,AMD A9-Series 9420 3GHz,3,6,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...
1298,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,0.0,Intel Atom X5-Z8350 1.44GHz,3,10,1,1.35kg,196.00
1299,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 6200U 2.3GHz,1,4,1,1.28kg,935.00
1300,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i5 8250U 1.6GHz,1,4,2,1.95kg,1199.00
1301,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i7 8550U 1.8GHz,2,4,2,1.95kg,1399.95
1302,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 7200U 2.5GHz,1,4,2,1.3kg,999.90

In [121]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,OpSys,Weight,Price_euros
0,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,0.0,Intel Core i5 7300HQ 2.5GHz,1,3,3,2.4kg,709.00
1,Acer,Aspire A515-51G-32MX,1,1,0.0,Intel Core i3 7130U 2.7GHz,3,3,1,2.2kg,530.00
2,Acer,Aspire 5,1,1,1.0,AMD A12-Series 9720P 2.7GHz,1,4,1,2.2kg,659.00
3,Acer,Aspire E5-575,1,1,1.0,Intel Core i5 7200U 2.5GHz,6,3,1,2.23kg,549.00
4,Acer,Aspire 3,1,1,1.0,AMD A9-Series 9420 3GHz,3,6,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...
1298,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,0.0,Intel Atom X5-Z8350 1.44GHz,3,10,1,1.35kg,196.00
1299,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 6200U 2.3GHz,1,4,1,1.28kg,935.00
1300,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i5 8250U 1.6GHz,1,4,2,1.95kg,1199.00
1301,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i7 8550U 1.8GHz,2,4,2,1.95kg,1399.95
1302,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 7200U 2.5GHz,1,4,2,1.3kg,999.90

In [122]:
df.duplicated().sum()

np.int64(28)

In [123]:
df.dropna(inplace=True)

In [124]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,OpSys,Weight,Price_euros
0,Acer,A715-71G-59DH (i5-7300HQ/8GB/1TB/GeForce,3,1,0.0,Intel Core i5 7300HQ 2.5GHz,1,3,3,2.4kg,709.00
1,Acer,Aspire A515-51G-32MX,1,1,0.0,Intel Core i3 7130U 2.7GHz,3,3,1,2.2kg,530.00
2,Acer,Aspire 5,1,1,1.0,AMD A12-Series 9720P 2.7GHz,1,4,1,2.2kg,659.00
3,Acer,Aspire E5-575,1,1,1.0,Intel Core i5 7200U 2.5GHz,6,3,1,2.23kg,549.00
4,Acer,Aspire 3,1,1,1.0,AMD A9-Series 9420 3GHz,3,6,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...,...
1298,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),1,5,0.0,Intel Atom X5-Z8350 1.44GHz,3,10,1,1.35kg,196.00
1299,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 6200U 2.3GHz,1,4,1,1.28kg,935.00
1300,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i5 8250U 1.6GHz,1,4,2,1.95kg,1199.00
1301,Xiaomi,Mi Notebook,1,1,4.0,Intel Core i7 8550U 1.8GHz,2,4,2,1.95kg,1399.95
1302,Xiaomi,Mi Notebook,2,5,4.0,Intel Core i5 7200U 2.5GHz,1,4,2,1.3kg,999.90

In [136]:
df['TypeName'].unique()

array([3, 1, 4, 5, 2, 6])

In [126]:
df = df.drop(columns=['Product'])

In [127]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,OpSys,Weight,Price_euros
0,Acer,3,1,0.0,Intel Core i5 7300HQ 2.5GHz,1,3,3,2.4kg,709.00
1,Acer,1,1,0.0,Intel Core i3 7130U 2.7GHz,3,3,1,2.2kg,530.00
2,Acer,1,1,1.0,AMD A12-Series 9720P 2.7GHz,1,4,1,2.2kg,659.00
3,Acer,1,1,1.0,Intel Core i5 7200U 2.5GHz,6,3,1,2.23kg,549.00
4,Acer,1,1,1.0,AMD A9-Series 9420 3GHz,3,6,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...,...
1298,Vero,1,5,0.0,Intel Atom X5-Z8350 1.44GHz,3,10,1,1.35kg,196.00
1299,Xiaomi,2,5,4.0,Intel Core i5 6200U 2.3GHz,1,4,1,1.28kg,935.00
1300,Xiaomi,1,1,4.0,Intel Core i5 8250U 1.6GHz,1,4,2,1.95kg,1199.00
1301,Xiaomi,1,1,4.0,Intel Core i7 8550U 1.8GHz,2,4,2,1.95kg,1399.95
1302,Xiaomi,2,5,4.0,Intel Core i5 7200U 2.5GHz,1,4,2,1.3kg,999.90

In [128]:
df = df.drop(columns=['ScreenResolution'])

In [129]:
df

,Company,TypeName,Inches,Cpu,Ram,Memory,OpSys,Weight,Price_euros
0,Acer,3,1,Intel Core i5 7300HQ 2.5GHz,1,3,3,2.4kg,709.00
1,Acer,1,1,Intel Core i3 7130U 2.7GHz,3,3,1,2.2kg,530.00
2,Acer,1,1,AMD A12-Series 9720P 2.7GHz,1,4,1,2.2kg,659.00
3,Acer,1,1,Intel Core i5 7200U 2.5GHz,6,3,1,2.23kg,549.00
4,Acer,1,1,AMD A9-Series 9420 3GHz,3,6,1,2.1kg,426.00
...,...,...,...,...,...,...,...,...,...
1298,Vero,1,5,Intel Atom X5-Z8350 1.44GHz,3,10,1,1.35kg,196.00
1299,Xiaomi,2,5,Intel Core i5 6200U 2.3GHz,1,4,1,1.28kg,935.00
1300,Xiaomi,1,1,Intel Core i5 8250U 1.6GHz,1,4,2,1.95kg,1199.00
1301,Xiaomi,1,1,Intel Core i7 8550U 1.8GHz,2,4,2,1.95kg,1399.95
1302,Xiaomi,2,5,Intel Core i5 7200U 2.5GHz,1,4,2,1.3kg,999.90

In [130]:
df = df.drop(columns=['Cpu'])

In [131]:
df = df.drop(columns=['Weight'])

In [132]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1298    Vero         1       5    3      10      1       196.00
1299  Xiaomi         2       5    1       4      1       935.00
1300  Xiaomi         1       1    1       4      2      1199.00
1301  Xiaomi         1       1    2       4      2      1399.95
1302  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [133]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1298    Vero         1       5    3      10      1       196.00
1299  Xiaomi         2       5    1       4      1       935.00
1300  Xiaomi         1       1    1       4      2      1199.00
1301  Xiaomi         1       1    2       4      2      1399.95
1302  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [134]:
df.to_csv('laptop_clean.csv')

In [135]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1298    Vero         1       5    3      10      1       196.00
1299  Xiaomi         2       5    1       4      1       935.00
1300  Xiaomi         1       1    1       4      2      1199.00
1301  Xiaomi         1       1    2       4      2      1399.95
1302  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]